services:
  postgres:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: swgoh
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d swgoh"]
      interval: 3s
      timeout: 5s
      retries: 5

  comlink:
    image: ghcr.io/swgoh-utils/swgoh-comlink:latest
    container_name: swgoh-comlink
    environment:
      APP_NAME: comlink
    ports:
      - 3000:3000
    
  bot:
    build: .
    container_name: swgoh-bot
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/swgoh
      COMLINK_URL: http://comlink:3000
    depends_on:
      postgres:
        condition: service_healthy
      comlink:
        condition: service_started

volumes:
  postgres: